name: Black Formatting altered files only

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run black on diffed files
        run: git diff --name-only "$GITHUB_BASE_REF..$GITHUB_SHA" | xargs black --check --fast